"""
Configuration settings for the Coffee Agent application.
These values can be customized via environment variables.
"""
import os
from dotenv import load_dotenv

load_dotenv()

# OpenAI Configuration
# Use gpt-4o by default for faster responses (~5–8s). Set OPENAI_MODEL=gpt-5 for best quality (slower).
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o")
OPENAI_MAX_TOKENS = int(os.getenv("OPENAI_MAX_TOKENS", "4096"))
OPENAI_TEMPERATURE = float(os.getenv("OPENAI_TEMPERATURE", "1"))
OPENAI_TIMEOUT_SEC = int(os.getenv("OPENAI_TIMEOUT_SEC", "30"))

# User Timezone Configuration (for calendar "today"/"yesterday" range)
# Use IANA name (e.g. America/Los_Angeles, Asia/Kolkata) so server can compute UTC ranges correctly.
USER_TIMEZONE = os.getenv("USER_TIMEZONE", "PDT")
USER_TIMEZONE_OFFSET = os.getenv("USER_TIMEZONE_OFFSET", "UTC-8")
USER_TIMEZONE_IANA = os.getenv("USER_TIMEZONE_IANA", "America/Los_Angeles")

# Function Names 
FUNCTION_GMAIL_FETCH_MAILS = "GMAIL_FETCH_MAILS"
FUNCTION_CALENDAR_FETCH_EVENTS = "GOOGLECALENDAR_FETCH_EVENTS"
FUNCTION_CALENDAR_CREATE_EVENT = "GOOGLECALENDAR_CREATE_EVENT"
FUNCTION_NOTION_CREATE_PAGE = "NOTION_CREATE_PAGE"
FUNCTION_NOTION_SEARCH_PAGES = "NOTION_SEARCH_PAGES"
FUNCTION_GITHUB_LIST_REPOSITORIES = "GITHUB_LIST_REPOSITORIES"
FUNCTION_GITHUB_LIST_ISSUES = "GITHUB_LIST_ISSUES"
FUNCTION_GITHUB_CREATE_ISSUE = "GITHUB_CREATE_ISSUE"
FUNCTION_SLACK_SEND_MESSAGE = "SLACK_SEND_MESSAGE"
FUNCTION_SLACK_LIST_CHANNELS = "SLACK_LIST_CHANNELS"
FUNCTION_SLACK_FETCH_CONVERSATION_HISTORY = "SLACK_FETCH_CONVERSATION_HISTORY"
FUNCTION_SLACK_CREATE_CHANNEL = "SLACK_CREATE_CHANNEL"
FUNCTION_SLACK_LIST_USERS = "SLACK_LIST_USERS"
FUNCTION_HUBSPOT_LIST_CONTACTS = "HUBSPOT_LIST_CONTACTS"
FUNCTION_HUBSPOT_CREATE_CONTACT = "HUBSPOT_CREATE_CONTACT"
FUNCTION_HUBSPOT_SEARCH_CONTACTS = "HUBSPOT_SEARCH_CONTACTS"
FUNCTION_HUBSPOT_LIST_COMPANIES = "HUBSPOT_LIST_COMPANIES"
